version: '2.3'

# list of services in the Docker
services:

  # picpurify container configuration
  pd-picpurify:
    container_name: pd-picpurify
    # image:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - '${FASTAPI_LOCAL_PORT}:${FASTAPI_DOCKER_PORT}'

    environment:
      # picpurify env
      POINT_DUTY_ENV: ${POINT_DUTY_ENV}
      NVIDIA_VISIBLE_DEVICES: all