version: '3.0'

# list of services in the Docker
services:

  # vid_search_engin container configuration
  pd_vid_search_engin:
    container_name: pd_vid_search_engin
    # image:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - '${FASTAPI_LOCAL_PORT}:${FASTAPI_DOCKER_PORT}'

    environment:
      # vid_search_engin env
      POINT_DUTY_ENV: ${POINT_DUTY_ENV}

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6377:6379"
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    user: "1000:1000"
    restart: always
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - pd_vid_search_engin
      - redis
    links:
      - redis

  # celery_beat_worker:
  #   container_name: celery_beat_worker
  #   build: .
  #   command: celery -A celery_worker.celery beat --loglevel=info
  #   user: "1000:1000"
  #   volumes:
  #     - .:/code
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  #   links:
  #   - celery_worker
  #   - redis
  #   depends_on:
  #   - pd_vid_search_engin
  #   - celery_worker
  #   - redis

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.celery flower --port=5555
    user: "1000:1000"
    restart: always
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    # depends_on:
    #   - pd_vid_search_engin
    #   - redis
    #   - celery_worker
    links:
      - redis
      - celery_worker
      - pd_vid_search_engin
    # - celery_beat_worker
    depends_on:
      - pd_vid_search_engin
      - redis
      - celery_worker
    # - celery_beat_worker
