version: '2.4'

# list of services in the Docker
services:

  # python container configuration
  point_duty_ocr:
    container_name: point_duty_ocr
    # image:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - ${FASTAPI_LOCAL_PORT}:${FASTAPI_DOCKER_PORT}
    depends_on:
      - point_duty_deepstack
    runtime: nvidia
    shm_size: "4gb"

    environment:
      # python env
      POINT_DUTY_ENV: ${POINT_DUTY_ENV}
      NVIDIA_VISIBLE_DEVICES: all

  # point-duty-deepstack service
  point_duty_deepstack:
    container_name: point_duty_deepstack
    image: deepquestai/deepstack
    # build: .
    ports:
      - ${DEEPSTACK_LOCAL_PORT}:${DEEPSTACK_DOCKER_PORT}
    environment:
      # - VISION-DETECTION=True
      - VISION-SCENE=True
      # - API-KEY=""