version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  container_name: x-minio-common
  image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
  command: server --console-address ":${MINIO_SECOENDRY_PORT}" http://minio{1...4}/data{1...2}
  expose:
    - "${MINIO_MAIN_PORT}"
    - "${MINIO_SECOENDRY_PORT}"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    MINIO_DOMAIN: pd-domain.com
    MINIO_PUBLIC_IPS: 192.168.20.200
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:${MINIO_MAIN_PORT}/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${MINIO_MAIN_PORT}:${MINIO_MAIN_PORT}"
      - "${MINIO_SECOENDRY_PORT}:${MINIO_SECOENDRY_PORT}"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: