version: '3.0'

# list of services in the Docker
services:

  # detectron2 container configuration
  pd-qr:
    container_name: pd-qr
    # image:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - '${FASTAPI_LOCAL_PORT}:${FASTAPI_DOCKER_PORT}'

    environment:
      # detectron2 env
      POINT_DUTY_ENV: ${POINT_DUTY_ENV}


  # webhook:
  #   image: "fredsted/webhook.site"
  #   # Enable build for development:
  #   # build:
  #   #   dockerfile: Dockerfile
  #   #   context: ./
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   command: php artisan queue:work --daemon --tries=3 --timeout=10
  #   ports:
  #     - "8084:80"
  #   environment:
  #     - APP_ENV=dev
  #     - APP_DEBUG=true
  #     - APP_URL=http://localhost:8084
  #     - APP_LOG=errorlog
  #     - DB_CONNECTION=sqlite
  #     - REDIS_HOST=redis
  #     - BROADCAST_DRIVER=redis
  #     - CACHE_DRIVER=redis
  #     - QUEUE_DRIVER=redis
  #     - ECHO_HOST_MODE=path

  # redis:
  #   image: "redis:alpine"

  # laravel-echo-server:
  #   image: "mintopia/laravel-echo-server"
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   environment:
  #     - LARAVEL_ECHO_SERVER_AUTH_HOST=http://webhook
  #     - LARAVEL_ECHO_SERVER_HOST=0.0.0.0
  #     - LARAVEL_ECHO_SERVER_PORT=6001
  #     - ECHO_REDIS_PORT=6379
  #     - ECHO_REDIS_HOST=redis
  #     - ECHO_PROTOCOL=http
  #     - ECHO_ALLOW_CORS=true
  #     - ECHO_ALLOW_ORIGIN=*
  #     - ECHO_ALLOW_METHODS=*
  #     - ECHO_ALLOW_HEADERS=*