version: '3.0'

# list of services in the Docker
services:
  # point-duty-phpMyAdmin for local db container configuration
  point-duty-phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: point-duty-phpMyAdmin
    environment:
      # PMA_ARBIRARY: 1
      PMA_HOSTS: ${PMA_HOSTS}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - ${PMA_LOCAL_PORT}:${PMA_DOCKER_PORT}
    depends_on:
      - point-duty-mariaDB

  # Maria db container configuration
  point-duty-mariaDB:
    container_name: point-duty-mariaDB
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    command: mysqld --max_allowed_packet=512M --sql_mode="NO_ENGINE_SUBSTITUTION"
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}

  #service for cache
  point-duty-redis:
    container_name: point-duty-redis
    restart: always
    image: redis:latest
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - redisdata:/data
volumes:
  redisdata:
