version: '3.0'

# list of services in the Docker
services:
  pd_adminer:
    container_name: pd_adminer
    image: adminer
    restart: always
    depends_on:
      - point_duty_mssql
    ports:
      - "${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}"

  point_duty_mssql:
    container_name: point_duty_mssql
    build: .
    image: mcmoe/mssqldocker:v2017.CU24.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_USER: ${MSSQL_ROOT_USERNAME}
      MSSQL_PASSWORD: ${MSSQL_ROOT_PASSWORD}
    ports:
      - "${MSSQL_LOCAL_PORT}:${MSSQL_DOCKER_PORT}"
