version: '3.0'

# list of services in the Docker
services:
  adminer:
    image: adminer
    restart: always
    depends_on:
      - point-duty-mssql
    ports:
      - "${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}"

  point-duty-mssql:
    build: .
    image: mcmoe/mssqldocker:v2017.CU24.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_USER: ${MSSQL_ROOT_USERNAME}
      MSSQL_PASSWORD: ${MSSQL_ROOT_PASSWORD}
    ports:
      - "${MSSQL_LOCAL_PORT}:${MSSQL_DOCKER_PORT}"
    container_name: point-duty-mssql

  #service for cache
  point-duty-redis:
    container_name: point-duty-redis
    restart: always
    image: redis:latest
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    volumes:
      - redisdata:/data
volumes:
  redisdata:
